### ISSUE TITLE
[Nintendo DS] Compilation clones? 

### ISSUE THREAD

**Issue by retroNUC** [unexpectedpanda/retool-clonelists-metadata#25]
- `Atlantic Quest + Galactic Quest (Europe) (En,Fr,De,Nl)`
- `Jewel Link Double Pack (Europe)`

These two games are both compilations, but also both clones of _**each other**_. Both are tagged as compilations of their respective individual games in clone lists, and the individual ones get filtered out, but both compilations still end up in the final output.

```
+ Atlantic Quest + Galactic Quest (Europe) (En,Fr,De,Nl)
  - Atlantic Quest (Europe) (Fr,De)
  - Jewel Link - Atlantic Quest (Europe)
  - Jewel Link - Atlantic Quest (Europe) (Fr,Nl)
  - Jewel Link - Galactic Quest (Europe)

+ Jewel Link Double Pack (Europe)     *no clones*
```

Tried adding a new entry in the clone lists to group the two compilations together, but no luck. Does it need a more complicated definition, or is it a logic issue?

**Comment by unexpectedpanda** [comment]
Compilations automatically get associated with each other by being defined as compilations for different individual titles.

In this case, the issue is there's a tie between the compilations &mdash; Retool can't decide which is better. If you set a priority of `2` for one of them, the lower priority title gets dismissed during the compilation comparison phase. Retool then can't decide if the remaining compilation is better than the individual titles, and so falls back on said individual titles.

```json
{
  "group": "Jewel Link - Atlantic Quest",
  "titles": [
    {"searchTerm": "Jewel Link - Atlantic Quest"},
    {"searchTerm": "Atlantic Quest", "priority": 2}
  ],
  "compilations": [
    {"searchTerm": "Atlantic Quest + Galactic Quest"},
    {"searchTerm": "Jewel Link Double Pack", "priority": 2}
  ]
},
{
  "group": "Jewel Link - Galactic Quest",
  "titles": [
    {"searchTerm": "Jewel Link - Galactic Quest"}
  ],
  "compilations": [
    {"searchTerm": "Atlantic Quest + Galactic Quest"},
    {"searchTerm": "Jewel Link Double Pack", "priority": 2}
  ]
},
```

Given languages have been specified on one title, I'm leaning toward making that the higher priority. And perhaps I should cycle through all languages as a tie-breaker later on...
