### ISSUE TITLE
About MPT

### ISSUE THREAD

**Issue by rufotheone-fr** [unexpectedpanda/retool-clonelists-metadata#47]
I think that we should make Metroid Prime Trilogy a superset because Wii versions of MP1 & 2 were released only in JP (and so, Retool keeps those + Trilogy).

**Comment by unexpectedpanda** [comment]
Ah, thanks for the clarification. Making it a superset won't do that. In fact, it'll end up the same as it is now -- Metroid Prime Trilogy will still get selected unless Japanese is higher in your region order than English.

You can only get the outcome you want if [more compilation options are made available](https://github.com/unexpectedpanda/retool/issues/277#issuecomment-1644825457) &mdash; and that's a feature that's a long way away.

Since there's already a feature request for this, I'll close this particular issue as a duplicate.
