### ISSUE TITLE
SNES Clonelist - Super Mario World and Allstars

### ISSUE THREAD

**Issue by Archangel54** [unexpectedpanda/retool-clonelists-metadata#56]
Hello,

I would like to know why "Super Mario All-Stars + Super Mario World" and "Super Mario All-Stars and Super Mario World" are considered as supersets instead of compilations IMO ?

```python
"group": "Super Mario All-Stars",
	"titles": [
		{"searchTerm": "Super Mario All-Stars"},
		{"searchTerm": "Super Mario Collection"}
	],
	"supersets": [
		{"searchTerm": "Super Mario All-Stars + Super Mario World"},
		{"searchTerm": "Super Mario All-Stars and Super Mario World"}
	]

"group": "Super Mario World",
	"titles": [
		{"searchTerm": "Super Mario World"},
		{"searchTerm": "Super Mario World - Super Mario Bros. 4"}
	],
	"supersets": [
		{"searchTerm": "Super Mario All-Stars + Super Mario World"},
		{"searchTerm": "Super Mario All-Stars and Super Mario World"}
	]
``` 

It should be
```python
"group": "Super Mario All-Stars",
	"titles": [
		{"searchTerm": "Super Mario All-Stars"},
		{"searchTerm": "Super Mario Collection"}
	],
	"compilations": [
		{"searchTerm": "Super Mario All-Stars + Super Mario World"},
		{"searchTerm": "Super Mario All-Stars and Super Mario World"}
	]

"group": "Super Mario World",
	"titles": [
		{"searchTerm": "Super Mario World"},
		{"searchTerm": "Super Mario World - Super Mario Bros. 4"}
	],
	"compilations": [
		{"searchTerm": "Super Mario All-Stars + Super Mario World"},
		{"searchTerm": "Super Mario All-Stars and Super Mario World"}
	]
```

**Comment by unexpectedpanda** [comment]
Most people ask this because they want the individual titles to be selected by Retool instead of the compilations, whether for speed running, retroachievements, or otherwise. I"m guessing you also want the individual games? If so, I'd be interested to hear the reason.

The compilation contains [updated versions of the games](https://www.mariowiki.com/Super_Mario_All-Stars_%2B_Super_Mario_World), so it's in line with Retool's ethos to select them over the individual titles. Marking them as `supersets` is one way to achieve this. I could (and probably should) change it to `compilations`, but a heads up &mdash; I'd also set the individual titles to a priority of 2, which means the compilations would still be chosen over the individual titles.

**Comment by Archangel54** [comment]
I ask this because for my 1g1r sets, I prefer individual ROMs instead of compilations.
This is due to nostalgia (I had this game when I was young and not the compilation ^^ ) and also for practical reasons, as it is easier to locate a ROM in an alphabetically ordered list if it is not part of a compilation.

**Comment by unexpectedpanda** [comment]
Adding more compilation options has [long been under discussion](https://github.com/unexpectedpanda/retool/issues/252).

One day, perhaps, but it's very low priority as it's quite complicated code to deal with.
